"""Initial_schema

Revision ID: 61148edbe54c
Revises: 
Create Date: 2026-05-06 17:03:58.843526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '61148edbe54c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contratos',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('contract_number', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('main_hash', sa.String(), nullable=True),
    sa.Column('empenhos_hash', sa.String(), nullable=True),
    sa.Column('faturas_hash', sa.String(), nullable=True),
    sa.Column('historico_hash', sa.String(), nullable=True),
    sa.Column('garantias_hash', sa.String(), nullable=True),
    sa.Column('responsaveis_hash', sa.String(), nullable=True),
    sa.Column('itens_hash', sa.String(), nullable=True),
    sa.Column('raw_contract', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_empenhos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_faturas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_garantias', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_historico', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_responsaveis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_itens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_main_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_operational_update_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contratos_contract_number'), 'contratos', ['contract_number'], unique=False)
    op.create_index(op.f('ix_contratos_external_id'), 'contratos', ['external_id'], unique=True)
    op.create_table('alertas',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('contract_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notification_count', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alertas_contract_id'), 'alertas', ['contract_id'], unique=False)
    op.create_index(op.f('ix_alertas_status'), 'alertas', ['status'], unique=False)
    op.create_index(op.f('ix_alertas_type'), 'alertas', ['type'], unique=False)
    op.create_table('alert_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('performed_by', sa.String(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_history_alert_id'), 'alert_history', ['alert_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('alert_id', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_alert_id'), 'notifications', ['alert_id'], unique=False)
    op.create_index(op.f('ix_notifications_status'), 'notifications', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_status'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_alert_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_alert_history_alert_id'), table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_index(op.f('ix_alertas_type'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_status'), table_name='alertas')
    op.drop_index(op.f('ix_alertas_contract_id'), table_name='alertas')
    op.drop_table('alertas')
    op.drop_index(op.f('ix_contratos_external_id'), table_name='contratos')
    op.drop_index(op.f('ix_contratos_contract_number'), table_name='contratos')
    op.drop_table('contratos')
    # ### end Alembic commands ###
