"""Add_sync_executions_and_status_columns

Revision ID: f54674e70a57
Revises: 61148edbe54c
Create Date: 2026-05-06 22:34:12.564927

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f54674e70a57'
down_revision = '61148edbe54c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_executions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('last_page_processed', sa.Integer(), nullable=True),
    sa.Column('processed_contracts', sa.Integer(), nullable=True),
    sa.Column('failed_contracts', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_executions_status'), 'sync_executions', ['status'], unique=False)
    op.create_index(op.f('ix_sync_executions_type'), 'sync_executions', ['type'], unique=False)
    op.add_column('contratos', sa.Column('empenhos_status', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('faturas_status', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('historico_status', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('garantias_status', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('responsaveis_status', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('itens_status', sa.String(), nullable=True))
    op.add_column('contratos', sa.Column('last_success_sync_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('contratos', sa.Column('last_failed_sync_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contratos', 'last_failed_sync_at')
    op.drop_column('contratos', 'last_success_sync_at')
    op.drop_column('contratos', 'itens_status')
    op.drop_column('contratos', 'responsaveis_status')
    op.drop_column('contratos', 'garantias_status')
    op.drop_column('contratos', 'historico_status')
    op.drop_column('contratos', 'faturas_status')
    op.drop_column('contratos', 'empenhos_status')
    op.drop_index(op.f('ix_sync_executions_type'), table_name='sync_executions')
    op.drop_index(op.f('ix_sync_executions_status'), table_name='sync_executions')
    op.drop_table('sync_executions')
    # ### end Alembic commands ###
